# -*- coding: utf-8 -*-
"""Cópia de ListaExercicios_1_PythonExpress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nruyCca-f4tOz42Q7h6n_Ze0q2rZayty

***
## **<center>Lista de Exercícios 1 - Python Express</center>**


**<center>Introdução a Ciência de Dados</center>**
***

<br>

Segue uma lista de exercícios abordando o conteúdo inicial para a programação em Python.

Cada exercício deve ser respondido em uma célula específica.


1) Elabore um código que imprima a mensagem *"Olá terráqueos!!"* na tela.


2) Elabore um código que peça um número e então mostre a mensagem: *"O número informado foi [número]."*


3) Elabore um código que peça dois números e imprima a soma.


4) Elabore um código que peça as 4 notas bimestrais e mostre a média.

5) Elabore um código que converta metros para centímetros.


6) Elabore um código que peça o raio de um círculo, calcule e mostre sua área.

7) Elabore um código que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.


8) Elabore um código que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês em uma mensagem amigável.


9) Elabore um código que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius.
** Onde C = 5 * ((F-32) / 9)**.


10) Elabore um código que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit.


11) Elabore um código que peça 2 números inteiros e um número real. Calcule e mostre:
* o produto do dobro do primeiro com metade do segundo .
* a soma do triplo do primeiro com o terceiro.
* o terceiro elevado ao cubo.

12) Elabore um código que receba os dados de entrada a altura de uma pessoa, e informe qual seria o peso ideal, usando a seguinte fórmula: (72.7*altura) - 58
"""

# 1) Elabore um código que imprima a mensagem *"Olá terráqueos!!"* na tela.

print("Olá terráqueos")

from ast import Num
# 2) Elabore um código que peça um número e então mostre a mensagem: "O número informado foi [número]."
Num=int(input("digite seu numero:"))
print("o numero informado foi",Num)

# 3) Elabore um código que peça dois números e imprima a soma.
num1=float(input("digite o primeiro valor:"))
num2=float(input("digite o segundo valor"))
soma=num1+num2
print("o valor da soma",soma)

# 4) Elabore um código que peça as 4 notas bimestrais e mostre a média.
nota1=int(input("digite a primeira nota"))
nota2=int(input("digite a segunda nota"))
nota3=int(input("digite a terceira nota"))
nota4=int(input("digite a quarta nota"))

media=nota1+nota2+nota3+nota4
total=media/4
print("o valor da media",total)

# 5) Elabore um código que converta metros para centímetros.
metros = float(input("Digite o valor em metros: "))
centimetros = metros * 100
print("O valor em centímetros é:", centimetros)

# 6) Elabore um código que peça o raio de um círculo, calcule e mostre sua área.
import math
raio = float(input("Digite o raio do círculo: "))
area = math.pi * (raio ** 2)
print("A área do círculo é:", area)

# 7) Elabore um código que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.

lado = float(input("Digite o valor do lado do quadrado: "))
area = lado ** 2
dobro = area * 2
print("A área do quadrado é:", area)
print("O dobro da área é:", dobro)

# 8) Elabore um código que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês em uma mensagem amigável.
valor_hora = float(input("Quanto você ganha por hora? R$ "))
horas_trabalhadas = float(input("Quantas horas você trabalhou no mês? "))
salario = valor_hora * horas_trabalhadas
print(f"\n💰 Seu salário neste mês foi de R$ {salario:.2f}. Parabéns pelo seu trabalho!")

# 9) Elabore um código que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius. ** Onde C = 5 * ((F-32) / 9)**.
fahrenheit = float(input("Digite a temperatura em Fahrenheit: "))
celsius = 5 * ((fahrenheit - 32) / 9)
print("A temperatura em Celsius é:", celsius)

# 10) Elabore um código que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit.
celsius = float(input("Digite a temperatura em Celsius: "))
fahrenheit = (9/5) * celsius + 32
print("A temperatura em Fahrenheit é:", fahrenheit)

# 11) Elabore um código que peça 2 números inteiros e um número real. Calcule e mostre:-o produto do dobro do primeiro com metade do segundo .-a soma do triplo do primeiro com o terceiro.-o terceiro elevado ao cubo.

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))
num3 = float(input("Digite um número real: "))
produto = (num1 * 2) * (num2 / 2)
soma = (num1 * 3) + num3
cubo = num3 ** 3
print("\nResultados:")
print("Produto do dobro do primeiro com metade do segundo:", produto)
print("Soma do triplo do primeiro com o terceiro:", soma)
print("Terceiro elevado ao cubo:", cubo)

# 12) Elabore um código que receba os dados de entrada a altura de uma pessoa, e informe qual seria o peso ideal, usando a seguinte fórmula: (72.7*altura) - 58
altura = float(input("Digite sua altura (em metros): "))
sexo = input("Digite seu sexo (M/F): ").upper()
if sexo == "M":
    peso_ideal = (72.7 * altura) - 58
elif sexo == "F":
    peso_ideal = (62.1 * altura) - 44.7
    print("Sexo inválido!")
    peso_ideal = None
if peso_ideal:
    print(f"Seu peso ideal é: {peso_ideal:.2f} kg")